### ISSUE TITLE
CI red: tests/impact.test.ts — all 6 tests fail (stale call signature, no graph fixtures)

### ISSUE THREAD

**Issue by ManSio** [GSF-001/ARCLUX#424]
## Symptom

`pnpm run test` fails on ARCLUX.main — `tests/impact.test.ts` fails 6/6:

```
FAIL tests/impact.test.ts > Impact Analysis > calculateAffectedFiles should return Set<string>
TypeError: repository.getModule is not a function
 ❯ traceConsumers packages/impact/traceConsumers.ts:18:34
```

## Root cause

The impact functions were refactored from `(moduleId, graph)` to `(repository, moduleId)` (see packages/impact/*), but the test file still calls them with the old signature:

```ts
calculateAffectedFiles("test.ts", repo.graph);   // old: (moduleId, graph)
// actual API: calculateAffectedFiles(repository, moduleId)
```

Additionally:
- `Repository` has no `graph` property (graph is built separately by `buildDependencyGraph`).
- `calculateAffectedFiles` returns `ImpactResult`, not `Set<string>` — the test asserts the wrong type.
- `repo` is an empty Repository — tests never exercise the actual impact mechanics.

Note: progres/bugs.md (2026-08-15) logged this as "mock/plain object doesn't implement getModule" — that diagnosis is inaccurate; the real cause is the stale call signature.

## Task

Rewrite `tests/impact.test.ts` with a real Repository populated with ModuleInfo fixtures (follow tests/graph.test.ts's makeModule/makeRepository convention):

- chain: A → B → C → change C → expect B, A affected
- circular: A → B → C → A → cycle guard (no infinite loop)
- fan-out: A → B, A → C
- nonexistent module: notFound behavior

Assert the actual affected sets / distances / tree shape, not just result types.

Refs: progres/bugs.md 2026-08-15 entry (Status: Not Started).
